### ISSUE TITLE
missing specs2-junit dependency

### ISSUE THREAD

**Issue by polentino** [davidB/scala-archetype-simple#22]
On a newly created project, running **mvn test** will produce the following error:

> [ERROR] /home/.../specs.scala:18: error: not found: type JUnitRunner
> [ERROR] @RunWith(classOf[JUnitRunner])

After adding the following dependency
`<dependency>`
`<groupId>org.specs2</groupId>`
`<artifactId>specs2-junit_${scala.compat.version}</artifactId>`
`<version>2.4.16</version>`
`</dependency>`

all the tests build and successfully pass.

**Comment by libasoles** [comment]
This is related to this: 
https://github.com/davidB/scala-archetype-simple/issues/21

Basically, we are not getting the latest pom.xml code. The one here:
https://github.com/davidB/scala-archetype-simple/blob/master/src/main/resources/archetype-resources/pom.xml

A workaround is copying the dependencies xml block (and also the configuration>args block because that prevents another error, the one I pointed in my link). Copying that xml blocks worked for me. 

Anyway, I'd love to know why I'm not getting the latest pom when using the 1.6v archetype.

**Comment by polentino** [comment]
@libasoles +1
I really would like to understand why, indeed.

**Comment by davidB** [comment]
Should be fixed with 1.7
