### ISSUE TITLE
main dependency on outdated archetype

### ISSUE THREAD

**Issue by kastoestoramadus** [davidB/scala-archetype-simple#27]
Hi,
Most guides of Scala with maven targets archetype:
https://mvnrepository.com/artifact/org.scala-tools.archetypes/scala-archetype-simple/1.3
From the website in it, I'm redirected to your blog.

Please tell me what is your relation to that artefact and tell if it's possible to use the source from this repo in main maven Scala artefact.
Now whoever tries Scala from Maven may get a very bad impression that this ecosystem is badly maintained.

I tried to create Scala project from Intelij Idea default archetypes list.

**Comment by davidB** [comment]
> Please tell me what is your relation to that artefact and tell if it's possible to use the source from this repo in main maven Scala artefact.

Started in 2008 (yes 12 yo), I contributed to the integration/bridge between scala & maven via scala-maven-plugin, this archetype, and the creation of scala-tools.org the first maven repository for scala artifacts (with packaging for scala-library, scala-compiler, ..., before pushing to maven central or jcenter was easy). And also some blog articles. Several years ago, the scala-tool.org server was shutdown, so I moved the maven plugin and archetype under my own domain net.alchim31 (also due to change in the maven policy from 2.x to 3.x).

Yes you can use this repo, fork it, contribute to it.

> Now whoever tries Scala from Maven may get a very bad impression that this ecosystem is badly maintained.

I stopped using scala and my interest moved to other domain (rust) few years ago. So the maintenance is only done by other contributors (on their spare time, like me before). By example slandelle keep maintain the scala-maven-plugin (also because it is used by its company).
This feeling is also caused by links to old deprecated articles.

I guess, you're right, the maven/scala is badly maintained by very few people. And the active contributor from scala community mainly focus on SBT (or alternatives gradle, mill ??).
 
> I tried to create Scala project from Intelij Idea default archetypes list.

TBH I didn't use this archetype a lot in the past (after few year), and at this time Eclipse was my main IDE (I also contributed to scala+eclipse).

I hope you have the response. Sorry for the bad experience, like I said contributions to the ecosystem are welcomes.

**Comment by slandelle** [comment]
> Now whoever tries Scala from Maven may get a very bad impression that this ecosystem is badly maintained.

Well, it's not an impression. It's the actual situation!
For several years, Scala support on maven has been relying on one single individual on whatever free time he can spare.

[According to Jetbrain](https://www.jetbrains.com/lp/devecosystem-2019/scala/), in 2019, maven was the second most popular build tool for Scala. Still, I can't say we're swamped with contributions...

**Comment by kastoestoramadus** [comment]
My bad. "Most guides of Scala with maven" is not true.
Most important guide has your target already:
https://docs.scala-lang.org/tutorials/scala-with-maven.html#creating-your-first-project

Intelij Idea has an outdated archetype and was my source of confusion. Issue created:
https://youtrack.jetbrains.com/issue/IDEA-255090
